document
prefix fmri <https://example.com/>
entity(fmri:anatomy-img1,[prov:label = "anatomy_img1" %% xsd:string])
entity(fmri:anatomy-hdr1,[prov:label = "anatomy_hdr1" %% xsd:string])
entity(fmri:anatomy-img2,[prov:label = "anatomy_img1" %% xsd:string])
entity(fmri:anatomy-hdr2,[prov:label = "anatomy_hdr2" %% xsd:string])
entity(fmri:anatomy-img3,[prov:label = "anatomy_img3" %% xsd:string])
entity(fmri:anatomy-hdr3,[prov:label = "anatomy_hdr3" %% xsd:string])
entity(fmri:anatomy-img4,[prov:label = "anatomy_img4" %% xsd:string])
entity(fmri:anatomy-hdr4,[prov:label = "anatomy_hdr4" %% xsd:string])
entity(fmri:reference-img,[prov:label = "reference_img" %% xsd:string])
entity(fmri:reference-hdr,[prov:label = "reference_hdr" %% xsd:string])
entity(fmri:warp1,[prov:label = "warp1" %% xsd:string])
entity(fmri:warp2,[prov:label = "warp2" %% xsd:string])
entity(fmri:warp3,[prov:label = "warp3" %% xsd:string])
entity(fmri:warp4,[prov:label = "warp4" %% xsd:string])
entity(fmri:resliced-img1,[prov:label = "resliced_img1" %% xsd:string])
entity(fmri:resliced-hdr1,[prov:label = "resliced_hdr1" %% xsd:string])
entity(fmri:resliced-img2,[prov:label = "resliced_img2" %% xsd:string])
entity(fmri:resliced-hdr2,[prov:label = "resliced_hdr2" %% xsd:string])
entity(fmri:resliced-img3,[prov:label = "resliced_img3" %% xsd:string])
entity(fmri:resliced-hdr3,[prov:label = "resliced_hdr3" %% xsd:string])
entity(fmri:resliced-img4,[prov:label = "resliced_img4" %% xsd:string])
entity(fmri:resliced-hdr4,[prov:label = "resliced_hdr4" %% xsd:string])
entity(fmri:atlas-hdr,[prov:label = "atlas_hdr" %% xsd:string])
entity(fmri:atlas-img,[prov:label = "atlas_img" %% xsd:string])
entity(fmri:slice-x,[prov:label = "slice_x" %% xsd:string])
entity(fmri:slice-y,[prov:label = "slice_y" %% xsd:string])
entity(fmri:slice-z,[prov:label = "slice_z" %% xsd:string])
entity(fmri:slice-x-img,[prov:label = "slice_x_image" %% xsd:string])
entity(fmri:slice-y-img,[prov:label = "slice_y_image" %% xsd:string])
entity(fmri:slice-z-img,[prov:label = "slice_z_image" %% xsd:string])
activity(fmri:align-warp1,2023-08-21T05:44:05.105+02:00,2023-08-21T05:44:05.361+02:00)
activity(fmri:align-warp2,2023-08-21T05:44:05.365+02:00,2023-08-21T05:44:05.617+02:00)
activity(fmri:align-warp3,2023-08-21T05:44:05.885+02:00,2023-08-21T05:44:06.137+02:00)
activity(fmri:align-warp4,2023-08-21T05:44:05.617+02:00,2023-08-21T05:44:05.881+02:00)
activity(fmri:reslice1,2023-08-21T05:44:07.121+02:00,2023-08-21T05:44:07.449+02:00)
activity(fmri:reslice2,2023-08-21T05:44:06.461+02:00,2023-08-21T05:44:06.793+02:00)
activity(fmri:reslice3,2023-08-21T05:44:06.137+02:00,2023-08-21T05:44:06.461+02:00)
activity(fmri:reslice4,2023-08-21T05:44:06.797+02:00,2023-08-21T05:44:07.117+02:00)
activity(fmri:softmean,2023-08-21T05:44:07.449+02:00,2023-08-21T05:44:08.525+02:00)
activity(fmri:slicer,2023-08-21T05:44:08.525+02:00,2023-08-21T05:44:10.789+02:00)
activity(fmri:convert,2023-08-21T05:44:10.793+02:00,2023-08-21T05:44:10.821+02:00)
agent(fmri:snakemake,[prov:label = "snakemake" %% xsd:string])
used(fmri:align-warp1,fmri:anatomy-img1,-)
used(fmri:align-warp1,fmri:anatomy-hdr1,-)
used(fmri:align-warp2,fmri:anatomy-img2,-)
used(fmri:align-warp2,fmri:anatomy-hdr2,-)
used(fmri:align-warp3,fmri:anatomy-img3,-)
used(fmri:align-warp3,fmri:anatomy-hdr3,-)
used(fmri:align-warp4,fmri:anatomy-img4,-)
used(fmri:align-warp4,fmri:anatomy-hdr4,-)
wasGeneratedBy(fmri:warp1,fmri:align-warp1,-)
wasGeneratedBy(fmri:warp2,fmri:align-warp2,-)
wasGeneratedBy(fmri:warp3,fmri:align-warp3,-)
wasGeneratedBy(fmri:warp4,fmri:align-warp4,-)
used(fmri:align-warp1,fmri:reference-hdr,-)
used(fmri:align-warp1,fmri:reference-img,-)
used(fmri:align-warp2,fmri:reference-hdr,-)
used(fmri:align-warp2,fmri:reference-img,-)
used(fmri:align-warp3,fmri:reference-hdr,-)
used(fmri:align-warp3,fmri:reference-img,-)
used(fmri:align-warp4,fmri:reference-hdr,-)
used(fmri:align-warp4,fmri:reference-img,-)
used(fmri:reslice1,fmri:warp1,-)
used(fmri:reslice2,fmri:warp2,-)
used(fmri:reslice3,fmri:warp3,-)
used(fmri:reslice4,fmri:warp4,-)
wasGeneratedBy(fmri:resliced-img1,fmri:reslice1,-)
wasGeneratedBy(fmri:resliced-hdr1,fmri:reslice1,-)
wasGeneratedBy(fmri:resliced-img2,fmri:reslice2,-)
wasGeneratedBy(fmri:resliced-hdr2,fmri:reslice2,-)
wasGeneratedBy(fmri:resliced-img3,fmri:reslice3,-)
wasGeneratedBy(fmri:resliced-hdr3,fmri:reslice3,-)
wasGeneratedBy(fmri:resliced-img4,fmri:reslice4,-)
wasGeneratedBy(fmri:resliced-hdr4,fmri:reslice4,-)
used(fmri:softmean,fmri:resliced-img1,-)
used(fmri:softmean,fmri:resliced-hdr1,-)
used(fmri:softmean,fmri:resliced-img2,-)
used(fmri:softmean,fmri:resliced-hdr2,-)
used(fmri:softmean,fmri:resliced-img3,-)
used(fmri:softmean,fmri:resliced-hdr3,-)
used(fmri:softmean,fmri:resliced-img4,-)
used(fmri:softmean,fmri:resliced-hdr4,-)
wasGeneratedBy(fmri:atlas-img,fmri:softmean,-)
wasGeneratedBy(fmri:atlas-hdr,fmri:softmean,-)
used(fmri:slicer,fmri:atlas-img,-)
used(fmri:slicer,fmri:atlas-hdr,-)
wasGeneratedBy(fmri:slice-x,fmri:slicer,-)
wasGeneratedBy(fmri:slice-y,fmri:slicer,-)
wasGeneratedBy(fmri:slice-z,fmri:slicer,-)
used(fmri:convert,fmri:slice-x,-)
used(fmri:convert,fmri:slice-y,-)
used(fmri:convert,fmri:slice-z,-)
wasGeneratedBy(fmri:slice-x-img,fmri:convert,-)
wasGeneratedBy(fmri:slice-y-img,fmri:convert,-)
wasGeneratedBy(fmri:slice-z-img,fmri:convert,-)
endDocument
